# Generated by Django 3.1.5 on 2021-01-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='short',
            field=models.CharField(default='default string', max_length=100),
        ),
    ]
