# Generated by Django 3.1.5 on 2021-01-21 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0011_auto_20210121_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectentry',
            name='technology',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
