# Generated by Django 3.1.5 on 2021-01-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0013_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/images'),
        ),
    ]
