# Generated by Django 3.1.5 on 2021-01-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0014_auto_20210121_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
