# Generated by Django 3.1.5 on 2021-01-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0016_auto_20210121_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectentry',
            name='image',
            field=models.FilePathField(default='', path='/img'),
            preserve_default=False,
        ),
    ]
