# Generated by Django 3.1.5 on 2021-01-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0017_projectentry_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectentry',
            name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
