# Generated by Django 3.1.5 on 2021-01-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0018_auto_20210121_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='new_site/new_sites/static/new_sites/images/'),
        ),
    ]
