# Generated by Django 3.1.5 on 2021-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0019_auto_20210121_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectentry',
            name='image',
            field=models.FileField(default='', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
