# Generated by Django 3.1.5 on 2021-01-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0021_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projectentry',
            name='image',
            field=models.FileField(upload_to='new_site/static/new_site/new_sites/static/new_sites/images/'),
        ),
    ]
