# Generated by Django 3.1.5 on 2021-01-29 12:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0026_auto_20210122_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectentry',
            name='project',
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectEntry',
        ),
    ]
