# Generated by Django 3.1.5 on 2021-01-29 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0027_auto_20210129_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='short',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='short',
        ),
    ]
