# Generated by Django 3.1.5 on 2021-02-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0034_auto_20210201_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='owner',
            field=models.CharField(max_length=255),
        ),
    ]
