# Generated by Django 3.1.5 on 2021-02-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0035_auto_20210201_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='article',
        ),
    ]
