# Generated by Django 3.1.5 on 2021-02-02 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_sites', '0036_auto_20210202_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='owner',
            new_name='user',
        ),
    ]
